# Introduction 

Organiser des données sous forme de tableaux est très répandu et très ancien car on retrouve des tables de données dans les livres de comptes de l'Egypte ancienne.

On peut organiser des données dans un tableau pour présenter des informations croisées, faire ses comptes, etc. Le bulletin d'un élève est une table qui indique pour chaque matière, la moyenne de l'élève, la moyenne de la classe, l'appréciation du professeur. La liste de présence des élèves est également représentée sous forme d'une table indiquant pour chaque élève s'il est présent ou absent ce jour.
 
En informatique, les tables de données sont rapidement devenues le principal moyen de stocker des données. L'analyse de ces données est utilisée dans de nombreux domaines : calcul scientifique, intelligence artificielle, programmation Web, bio-informatique, informatique financière, etc. De nombreuses données en tables sont disponibles sur les sites de données ouvertes.

**Exemple**

Voici un exemple de table avec des informations sur des élèves :

| **prénom** | **jour** | **mois** | **année** | **sexe** | **groupe** | **projet** |
| --- | --- | --- | --- | --- | --- | --- |
| Loona | 29 | 11 | 2005 | F | 1 | être heureuse |
| Quentin | 28 | 5 | 2005 | G | 2 | manger une glace |
| Sania | 30 | 7 | 2005 | F | 1 | gagner au loto |
| Yanis | 14 | 4 | 2005 | G | 1 | devenir quelqu’un de célèbre |
| Nolan | 16 | 4 | 2005 | G | 2 | avoir une bonne note au prochain devoir |
| Mathis | 12 | 1 | 2005 | G | 1 | devenir astronaute |
| Hippolyte | 20 | 10 | 2005 | G | 2 | marcher sur la lune |
| Martial | 22 | 4 | 2005 | G | 2 | dormir plus longtemps le matin |
| Arthur | 10 | 8 | 2005 | G | 2 | µaider les autres |
| Aïris | 24 | 3 | 2005 | F | 2 | apprendre à piloter une Formule 1 |

Pour exploiter ces données avec un ordinateur il est nécessaire de les mémoriser dans un fichier.

# Enregistrement et chargement des données

## Enregistrer les données dans un fichier

Il existe différents formats permettant de mémoriser les informations d'une table dans un fichier. Un des plus utilisés est le format **CSV** (pour **comma-separated values**, soit "données séparées par des virgules") qui est un fichier texte dans lequel :

- chaque ligne correspond à une ligne de la table ;
- chaque ligne est séparée en champs par une virgule (",") ;
- toutes les lignes du fichier ont le même nombre de champs ;
- on peut utiliser les guillemets droits (") pour délimiter le contenu des champs.

Ainsi, la table précédente peut être mémorisée dans un fichier CSV appelé `eleves.csv` dont voici le contenu :

```
"prénom","jour","mois","année","sexe","groupe","projet"
"Loona",29,11,2005,"F",1,"être heureuse"
"Quentin",28,5,2005,"G",2,"manger une glace"
"Sania",30,7,2005,"F",1,"gagner au loto"
"Yanis",14,4,2005,"G",1,"devenir quelqu’un de célèbre"
"Nolan",16,4,2005,"G",2,"avoir une bonne note au prochain devoir"
"Mathis",12,1,2005,"G",1,"devenir astronaute"
"Hippolyte",20,10,2005,"G",2,"marcher sur la lune"
"Martial",22,4,2005,"G",2,"dormir plus longtemps le matin"
"Arthur",10,8,2005,"G",2,"aider les autres"
"Aïris",24,3,2005,"F",2,"apprendre à piloter une Formule 1"
```

<img class="centre image-responsive" src="" alt="fichier texte">

<p style="text-align: center; color: #333;">Fichier CSV ouvert avec un éditeur de texte.</p>

Bien qu'étant un simple fichier texte, un fichier CSV peut être importé et exporté par un tableur qui permet d'en visualiser le contenu sous la forme d'un tableau.

>**Remarques** :
>- En France, le caractère de séparation des champs est généralement le point-virgule (";") car la virgule est utilisée pour écrire des nombres décimaux. Il faut donc être vigilant sur le caractère de séparation utilisé.
>- Le format CSV est apparu en 1972, soit bien avant l'avènement des ordinateurs personnels.

<img class="centre image-responsive" src="" alt="fichier texte">

<p style="text-align: center; color: #333;">Fichier CSV ouvert avec un tableur.</p>

### 🖊️ Exercice 1
---
Le fichier  `eleves.csv` est disponible à la racine de l'archive notebook que vous avez téléchargée.

1. Ouvrez ce fichier avec un éditeur de texte (gedit sous Ubuntu ou Bloc-notes sous Windows) pour en visualiser le contenu.
2. Ouvrez également ce fichier avec le tableur Calc de la suite LibreOffice pour en visualiser le contenu sous forme d'un tableau. *Il faudra vérifier que la caractère de séparation est bien la virgule*.

---

Pour exploiter et manipuler des tables de données mémorisées dans un fichier CSV, il faut commencer par *charger les données*. On pourra ensuite utiliser toute la puissance d'un langage de programmation pour les exploiter.

## Charger les données dans Python

Pour importer les données d'un fichier CSV dans Python il faut commencer par **ouvrir le fichier** avec Python. On utilise pour cela la fonction prédéfinie `open`.

In [ ]:
# on ouvre le fichier eleves.csv dans un objet appelé 'fichier'
fichier = open('eleves.csv', 'r', encoding = 'UTF-8')

>On a utilisé le paramètre `'r'` pour indiquer une ouverture en mode *lecture* (*read* en anglais).

Il faut ensuite **lire le fichier** pour charger son contenu dans Python. On pourrait pour cela utiliser la méthode `read` qui renvoie le contenu du fichier sous la forme d'une unique chaîne de caractères.

In [ ]:
texte = fichier.read() # on lit le contenu sous la forme d'une unique chaine de caractères
print(texte) # on affiche la chaine de caractères 'texte'

# on ferme le flux de lecture
fichier.close()

Cependant, ce n'est pas ainsi que l'on va procéder car exploiter cette grande chaîne de caractères n'est pas pratique. En effet, il sera beaucoup simple et efficace de manipuler des *types construits* comme les *tableaux* et surtout les *dictionnaires*.

Ainsi, on va plutôt lire le contenu du fichier pour **construire un tableau** dans lequel chaque élément correspond à une ligne de la table. Il est possible de représenter chaque ligne de la table :

- soit par un tableau, la table de données est alors représentée par un **tableau de tableaux** ;
- soit par un dictionnaire, la table de données est alors représentée par un **tableau de dictionnaires**.

Pour cela, la biliothèque standard de Python contient un module `csv` qui contient des fonctions très pratiques pour lire et écrire des fichiers CSV. La mémorisation dans un tableau devenant alors très rapide. Voici comment on procède.

### Chargement dans un tableau de tableaux

La méthode `reader` du module `csv` permet de lire la table ligne à ligne et renvoie successivement pour chaque ligne un tableau des champs de chaque ligne. La première ligne contient les noms des champs.

On peut alors construire par compréhension le tableau `eleves` qui mémorise toutes les données de la table, chaque élément de ce tableau étant lui-même un **tableau** correspondant à une ligne de la table de données.

In [ ]:
import csv # pour utiliser le module csv

# Ouverture du fichier
fichier = open('eleves.csv', 'r', encoding = 'UTF-8')

# Lecture de son contenu avec la méthode reader qui renvoie une valeur spéciale représentant le fichier CSV
table = csv.reader(fichier, delimiter=',')  # on précise le caractère de séparation, ici la virgule

# Construction par compréhension du tableau représentant la table
eleves = [ligne for ligne in table]  # chaque élément est un tableau

print(eleves) # pour afficher le contenu du tableau 'eleves'
fichier.close()

> 👀 Vous constaterez que l'on obtient alors un tableau de tableaux !

Chaque ligne est représentée par un tableau et on peut accéder à n'importe quelle donnée. Si on veut accéder aux informations sur le deuxième élève, on utilise l'instruction

In [ ]:
eleves[2]  # le 2ème élève est l'élément d'indice 3 car le premier élément reprend les noms de champs

De plus, comme on sait que c'est le champ d'indice 4 qui contient le sexe, on peut accéder au sexe du deuxième élève avec l'instruction

In [ ]:
eleves[2][4]

### 🖊️ Exercice 2
---

On considère la table précédente mémorisée dans le tableau (de tableaux) `eleves`.

**Question 1** : Les données sur le jour, le mois et l'année ont été mémorisées dans des variables de quel type ? Justifiez.

*Réponse* :

**Question 2** : Quelle instruction permet d'accéder au projet de Sania ?

In [ ]:
# à vous de jouer !

**Question 3** : Quelle instruction permet d'accéder à l'année de naissance de Léo ?

In [ ]:
# à vous de jouer !

**Question 4** : Complétez le programme ci-dessous afin qu'il affiche le prénom des élèves nés au mois d'avril.

In [ ]:
for eleve in eleves:
    if ...:
        print(...)

### Chargement dans un tableau de dictionnaires

La méthode `DictReader` permet de lire la table ligne à ligne et renvoie successivement pour chaque ligne un dictionnaire des champs de cette ligne. La première ligne du fichier a servi à obtenir les clés utilisées pour chaque enregistrement.

On peut alors construire par compréhension le tableau `eleves` qui mémorise toutes les données de la table, chaque élément de ce tableau étant un **dictionnaire** correspondant à une ligne de la table de données.

In [2]:
import csv # pour utiliser le module csv

# Ouverture du fichier
fichier = open('eleves.csv', 'r', encoding = 'UTF-8')

# Lecture de son contenu avec la méthode DictReader qui renvoie une valeur spéciale représentant le fichier CSV
table = csv.DictReader(fichier, delimiter=',')  # on précise le caractère de séparation, ici la virgule

# Construction par compréhension du tableau représentant la table
eleves = [dict(ligne) for ligne in table]  # chaque élément est un dictionnaire

fichier.close()

eleves  # pour voir le contenu

[{'prénom': 'Loona',
  'jour': '29',
  'mois': '11',
  'année': '2005',
  'sexe': 'F',
  'groupe': '1',
  'projet': 'être heureuse'},
 {'prénom': 'Quentin',
  'jour': '28',
  'mois': '5',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'manger une glace'},
 {'prénom': 'Sania',
  'jour': '30',
  'mois': '7',
  'année': '2005',
  'sexe': 'F',
  'groupe': '1',
  'projet': 'gagner au loto'},
 {'prénom': 'Yanis',
  'jour': '14',
  'mois': '4',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'devenir quelqu’un de célèbre'},
 {'prénom': 'Nolan',
  'jour': '16',
  'mois': '4',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'avoir une bonne note au prochain devoir'},
 {'prénom': 'Mathis',
  'jour': '12',
  'mois': '1',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'devenir astronaute'},
 {'prénom': 'Hippolyte',
  'jour': '20',
  'mois': '10',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'marcher sur la lune'},
 {'prénom': 'Martial',
  'jour': '22',
  'mois': '4',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'dormir plus longtemps le matin'},
 {'prénom': 'Arthur',
  'jour': '10',
  'mois': '8',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'aider les autres'},
 {'prénom': 'Aïris',
  'jour': '24',
  'mois': '3',
  'année': '2005',
  'sexe': 'F',
  'groupe': '2',
  'projet': 'apprendre à piloter une Formule 1'},
 {'prénom': 'Léo',
  'jour': '28',
  'mois': '7',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'devenir président'},
 {'prénom': 'Romain',
  'jour': '23',
  'mois': '1',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'créer un jeu vidéo'},
 {'prénom': 'Tanguy',
  'jour': '9',
  'mois': '6',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'gérer sa propre entreprise'},
 {'prénom': 'Nolwenn',
  'jour': '24',
  'mois': '11',
  'année': '2005',
  'sexe': 'F',
  'groupe': '2',
  'projet': 'jouer dans le prochain James Bond'},
 {'prénom': 'Célian',
  'jour': '17',
  'mois': '11',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'gagner le Tour de France'},
 {'prénom': 'Rayane',
  'jour': '23',
  'mois': '1',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'devenir champion du monde de bras de fer'},
 {'prénom': 'Ancelin',
  'jour': '15',
  'mois': '1',
  'année': '2007',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'devenir youtuber'},
 {'prénom': 'Ewen',
  'jour': '16',
  'mois': '5',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'avoir son émission de TV'},
 {'prénom': 'Nolan',
  'jour': '16',
  'mois': '5',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'écrire un livre'},
 {'prénom': 'Valentin',
  'jour': '8',
  'mois': '8',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'inventer la machine à voyager dans le temps'},
 {'prénom': 'Mathis',
  'jour': '14',
  'mois': '1',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'devenir une rockstar'},
 {'prénom': 'Jade',
  'jour': '14',
  'mois': '3',
  'année': '2005',
  'sexe': 'F',
  'groupe': '2',
  'projet': 'développer une application'},
 {'prénom': 'Charles',
  'jour': '23',
  'mois': '1',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'ouvrir un restaurant'},
 {'prénom': 'Sylliane',
  'jour': '7',
  'mois': '6',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'aller à Poudlard'},
 {'prénom': 'Clément',
  'jour': '6',
  'mois': '12',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'monter le tapis rouge à Cannes'},
 {'prénom': 'Kilian',
  'jour': '3',
  'mois': '11',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'gagner un Oscar'},
 {'prénom': 'Haroun',
  'jour': '27',
  'mois': '5',
  'année': '2004',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'devenir un joueur professionel de billard'},
 {'prénom': 'Hugo',
  'jour': '10',
  'mois': '1',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'sortir un film'},
 {'prénom': 'Lois',
  'jour': '17',
  'mois': '11',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'créer un objet révolutionnaire'},
 {'prénom': 'Agathe',
  'jour': '15',
  'mois': '7',
  'année': '2005',
  'sexe': 'F',
  'groupe': '2',
  'projet': "devenir championne du monde d'échecs"},
 {'prénom': 'Baptiste',
  'jour': '10',
  'mois': '12',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'manger des frites tous les jours à la cantine'},
 {'prénom': 'Sébastien',
  'jour': '14',
  'mois': '1',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'devenir champion olympique'},
 {'prénom': 'Nicolas',
  'jour': '24',
  'mois': '4',
  'année': '2006',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'participer à The Voice'},
 {'prénom': 'Maé',
  'jour': '18',
  'mois': '8',
  'année': '2005',
  'sexe': 'F',
  'groupe': '2',
  'projet': 'enregistrer un album'},
 {'prénom': 'Nolan',
  'jour': '25',
  'mois': '7',
  'année': '2005',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'acheter une Ferrari'},
 {'prénom': 'Timothé',
  'jour': '11',
  'mois': '1',
  'année': '2006',
  'sexe': 'G',
  'groupe': '1',
  'projet': 'participer au trophée Jules Verne'},
 {'prénom': 'Inès',
  'jour': '13',
  'mois': '12',
  'année': '2005',
  'sexe': 'F',
  'groupe': '1',
  'projet': 'battre le record du monde du marathon'},
 {'prénom': 'Kylian',
  'jour': '13',
  'mois': '3',
  'année': '2005',
  'sexe': 'G',
  'groupe': '2',
  'projet': 'battre Usain Bolt'}]

> 👀 Vous constaterez que l'on obtient un tableau de dictionnaires.

Chaque ligne est représentée par un dictionnaire et on peut accéder à n'importe quelle donnée. Si on veut accéder aux informations sur le deuxième élève, on utilise l'instruction

In [ ]:
eleves[1]  # attention le 2ème élève est l'élément d'indice 1 dans le tableau eleves

De plus, comme la clé du dictionnaire correspondant au sexe est `'sexe'`, on peut accéder au sexe du deuxième élève avec l'instruction

In [ ]:
eleves[1]['sexe'] # attention

### 🖊️ Exercice 3
---

On considère la table précédente mémorisée dans le tableau (de dictionnaires) `eleves`.

**Question 1** : Les données sur le jour, le mois et l'année ont été mémorisées dans des variables de quel type ? Justifiez.

*Réponse* :

**Question 2** : Quelle instruction permet d'accéder au projet de Sania ?

In [ ]:
# à vous de jouer !

**Question 3** : Quelle instruction permet d'accéder à l'année de naissance de Léo ?

In [ ]:
# à vous de jouer !

**Question 4** : Complétez le programme ci-dessous afin qu'il affiche le prénom des élèves nés au mois d'avril.

In [ ]:
for eleve in eleves:
    if ...:
        print(...)

### 🖊️ Exercice 4
---

Quel(s) avantage(s) présente la mémorisation des lignes de la table dans des dictionnaires par rapport à celle dans des tableaux ?

*Réponse* : 

---

>**Remarque** : Même en mémorisant chaque ligne de la table dans un dictionnaire, tout n'est pas encore parfait. En effet, pour trouver l'année de naissance de Léo, il faut savoir que la ligne le concernant a pour index 10 dans le tableau. Je vous laisse imaginer ce que cela peut donner pour trouver un index dans des fichiers de plusieurs dizaines de milliers de lignes...
>Heureusement, il est possible de chercher plus efficacement des données dans une table, c'est ce que nous allons voir maintenant.

# Rechercher un élément dans une table

>**Important** : on suppose dans toute la suite que les données ont été chargées dans un tableau de **dictionnaires**.

Une fois les données chargées dans une table, il est possible de travailler sur ces données en utilisant les opérations de manipulation sur les tableaux et les dictionnaires. En particulier, on va pouvoir effectuer une recherche en *parcourant le tableau* ligne par ligne, c'est-à-dire dictionnaire par dictionnaire.

## Présence d'un élément

On cherche ici à détecter la présence d'un élément dans une table (un élève dans notre cas). Nous allons utiliser des techniques de recherche dans un tableau comme celles dans le chapitre "Algorithmes de parcours séquentiel d'un tableau" (Thème 7, Chapitre 1). 

Pour rappel, voici la fonction `appartient` qui renvoie `True` ou `False` selon la présence ou l'absence d'un élément `v` dans un tableau `T`.

```python
def appartient(v, T):
    """Renvoie True si v appartient au tableau T, False sinon."""
    for e in T:
        if e == v:
            return True
    return False
```
On va légèrement adapter cette fonction pour chercher un élève désigné par son prénom dans notre table.

In [ ]:
def appartient(p, eleves):
    '''
    Renvoie True si le prénom p est dans le tableau eleves, et False sinon.
    p est un chaîne de caractères et eleves est un tableau de dictionnaires.
    '''
    for eleve in eleves:
        if eleve['prénom'] == p:
            return True
    return False

**Explications :** on passe en revue tous les éléments du tableau (chaque dictionnaire `eleve`) et on teste si l'un d'entre eux possède un attribut `'prénom'` égal à `p`, autrement dit si un des élèves a le prénom `p`.

On peut alors appeler cette fonction pour tester la présence d'un élève. 

>Pensez à exécuter à nouveau, si besoin, la première cellule du paragraphe précédent intitulé *Chargement dans un tableau de dictionnaires* qui charge les données de notre table dans le tableau `eleves`.

In [ ]:
appartient('Charles', eleves)

In [ ]:
appartient('Marie', eleves)

## Récupérer une donnée simple selon *un* critère
On peut adapter la fonction précédente pour qu'elle renvoie le projet de l'élève dont le prénom est entré en paramètre.

In [ ]:
def projet_de(p, eleves):
    '''
    Renvoie le projet de l'élève prénommé p dans le tableau eleves, et None si aucun prénom ne correspond.
    p est un chaîne de caractères et eleves est un tableau de dictionnaires.
    '''
    for eleve in eleves:
        if eleve['prénom'] == p:   # si un élève a le prénom p
            return eleve['projet'] # on renvoie le projet de cet élève
    return None

In [ ]:
projet_de('Sania', eleves)

> Vous remarquerez qu'avec cette façon de faire, il n'est plus nécessaire de connaître la position de Sania (son indice) dans la table, son prénom suffit désormais.

### 🖊️ Exercice 5
---

On souhaite écrire une fonction `sexe_de(p, eleves)` qui renvoie le sexe d'un élève de la table `eleves` dont le prénom `p` est entré en paramètre.

**Question 1** : Écrivez un bon jeu de tests pour cette fonction (avant d'écrire le code de la fonction, qui se fera en question 2). *Si besoin, se référer au chapitre 1 du thème 6 : [Documentation et mise au point de programmes](https://info-mounier.fr/premiere_nsi/langages_programmation/documentation_mise_au_point_de_programmes.php#Tester-ses-programmes-pour-(se)-convaincre)*.

In [ ]:
# à vous de jouer !

**Question 2** : Ecrivez la fonction `sexe_de(p, eleves)` qui renvoie le sexe d'un élève de la table `eleves` dont le prénom `p` est entré en paramètre, et `None` si aucun prénom ne correspond. Faites-lui passer vos tests et corrigez-la si besoin.

In [ ]:
# à vous de jouer !

### 🖊️ Exercice 6
---

On souhaite écrire une fonction qui renvoie l'âge (en 2022) d'un élève de la table dont le prénom est entré en paramètre, et `None` si aucun prénom ne correspond.

1. Choisissez un nom pour cette fonction et écrire sa chaîne de documentation.
2. Ecrivez un bon jeu de tests pour cette fonction.
3. Enfin, écrivez le code de cette fonction, qui doit passer tous les tests avec succès.

In [ ]:
# à vous de jouer !

## Récupérer une donnée simple selon *plusieurs* critères

Il est possible de préciser la recherche en combinant les conditions sur plusieurs attributs. On peut par exemple, rechercher le prénom d'un élève né l'année `a` **et** le mois `m`.

In [ ]:
def nom_eleve(a, m, eleves):
    ''' a et m sont des entiers et eleves est un tableau de dictionnaires '''
    for eleve in eleves:
        if int(eleve['année']) == a and int(eleve['mois']) == m:  # CONVERSION de l'année et du mois en des entiers (int)
            return eleve['prénom'] 
    return None

In [ ]:
nom_eleve(2005, 4, eleves)

**Remarques :** 
- On a pris soin de convertir les valeurs des attributs `'année'` et `'mois'` en type `int` pour comparer des variables de même type. 
- Il y avait trois élèves nés en avril 2005 (Yanis, Nolan et Martial) mais seul celui dont la ligne apparaît en premier a été renvoyé.

### 🖊️ Exercice 7 
---

**Question 1** : **Sans la tester**, que permet de faire la fonction suivante ?

In [ ]:
def mystere(a, s, eleves):
    ''' a est un entier, s est une chaine de caractères, eleves est un tableau de dictionnaires '''
    for eleve in eleves:
        if int(eleve['année']) == a and eleve['sexe'] == s:
            return eleve['prénom']
    return None

Réponse :

**Question 2** : Faites différents appels pour tester et valider/invalider votre réponse précédente.

In [ ]:
# à vous de jouer !

>**Remarque** : Les fonctions proposées parcourent la table ligne par ligne jusqu'à trouver la donnée correspondant aux critères de recherche, et la renvoie. Cependant, plusieurs lignes de la table (ici plusieurs élèves) peuvent correspondre à la recherche effectuée et on aimerait pouvoir rechercher *toutes* ces lignes (par exemple, renvoyer les prénoms de *tous* les élèves nés une certaine année et pas seulement le premier rencontré). Nous allons voir comment procéder dans le paragraphe suivant.

# Sélection de lignes

Toutes les opérations précédentes permettent de produire des résultats simples : afficher le projet d'un élève, ou son sexe, ou son prénom...

Or, dans le domaine du traitement de données, il est très souvent nécessaire d'extraire différentes données d'une table pour en construire une nouvelle. Par exemple, extraire tous les élèves qui sont nés un mois donné afin de leur souhaiter un bon anniversaire.

Pour cela, il suffit de **sélectionner les lignes** vérifiant une certaine condition pour produire une nouvelle table. Cette condition peut combiner plusieurs critères. Pour créer cette nouvelle table, on peut avantageusement la construire par compréhension.

**Syntaxe** 

On utilise la syntaxe classique d'une construction par compréhension mais en ajoutant une condition avec un `if` :
```python
selection = [ligne for ligne in table if criteres]
``` 
Ainsi, on crée un nouveau tableau `selection` qui contient uniquement les lignes du tableau `table` de départ qui vérifient la condition `criteres`, et pas les autres.

Par exemple, on peut créer un nouveau tableau `nes_en_aout` qui contient tous les (dictionnaires des) élèves de la table `eleves` qui sont nés en août.

In [ ]:
nes_en_aout = [eleve for eleve in eleves if int(eleve['mois']) == 8] 
nes_en_aout  # pour voir le tableau

Ce tableau `nes_en_aout` représente la nouvelle table de données suivante.

| **prénom** | **jour** | **mois** | **année** | **sexe** | **projet** |
| --- | --- | --- | --- | --- | --- |
| Arthur | 10 | 8 | 2005 | G | aider les autres |
| Valentin | 8 | 8 | 2005 | G | inventer la machine à voyager dans le temps |
| Maé | 18 | 8 | 2005 | F | enregistrer un album |

### 🖊️ Exercice 8
---

**Question 1** : À partir de la table `eleves`, contruire une table `filles` contenant toutes les filles.

In [ ]:
# à vous de jouer !

**Question 2** : À partir de la table `eleves`, contruire une table `groupe1` contenant les élèves du groupe 1.

In [ ]:
# à vous de jouer !

**Question 3** : À partir de la table `eleves`, contruire une table `nes_avril_2005` contenant les élèves nés en avril 2005.

In [ ]:
# à vous de jouer !

**Question 4** : À partir de la table `eleves`, contruire une table `t` contenant les élèves nés entre le 1er janvier 2005 et le 20 mai 2005.

In [ ]:
# à vous de jouer !

**Question 5** : Quelle instruction permet alors très rapidement de connaître le nombre d'élèves nés entre 1er janvier 2005 et le 20 mai 2005 ?

In [ ]:
# à vous de jouer !

---

>**Remarque** : On a sélectionné les lignes *complètes* correspondant à certains critères. Cela signifie que toutes les colonnes ont été ajoutées à la table créée. On peut aussi très facilement construire un nouveau tableau ne contenant que certaines colonnes de la table de départ, ce que nous allons voir maintenant pour terminer.

# Sélectionner des lignes et des colonnes

## Projection sur une ou plusieurs colonnes

Si on ne souhaite sélectionner que certaines colonnes de la table de départ, on dit que l'on fait une **projection sur ces colonnes**.

On peut construire un nouveau tableau en faisant une projection sur une seule colonne, par exemple les prénoms.

In [ ]:
t0 = [eleve['prénom'] for eleve in eleves]
t0

On peut aussi projeter sur plusieurs colonnes, en reconstruisant des dictionnaires ne contenant que les attributs souhaités, par exemple les prénoms et les projets :

In [ ]:
t1 = [{'prénom': eleve['prénom'], 'projet': eleve['projet']} for eleve in eleves]
t1

### 🖊️ Exercice 9
---

Construisez un tableau `t4` ne conservant que le prénom, l'année de naissance et le groupe de chaque élève de la table `eleves`.

In [ ]:
# à vous de jouer !

## Combiner les sélections sur les lignes et les colonnes

Il est bien sûr possible de combiner une sélection sur les colonnes avec une sélection sur les lignes. Ainsi, l'instruction

In [ ]:
t2 = [eleve['prénom'] for eleve in eleves if eleve['sexe'] == 'G']
t2

permet de créer un tableau contenant les prénoms des garçons. On a donc sélectionné la première colonne contenant les prénoms des élèves (avec `eleve[prénom]`) mais seulement pour les lignes correspondant à des garçons (avec le critère `if eleve['sexe'] == 'G')`.

On peut bien sûr aussi sélectionner plusieurs colonnes tout en sélectionnant certaines lignes. Par exemple, on peut sélectionner les attributs `'prénom'` et `'projet'` mais uniquement des filles.

In [ ]:
t3 = [{'prénom': eleve['prénom'], 'projet': eleve['projet']} for eleve in eleves if eleve['sexe'] == 'F']
t3

### 🖊️ Exercice 10 :
---

A partir de la table `eleves` construire un tableau `t4` contenant les prénoms des élèves nés en 2005. (Ancelin, Haroun, Nicolas et Timothé ne doivent pas s'y trouver).

In [ ]:
# à vous de jouer

### 🖊️ Exercice 11
---

**Question 1** : Construire une table `t5` contenant les prénoms et les années de naissance des garçons.

In [ ]:
# à vous de jouer !

**Question 2** : Construire une table `t6` ne contenant que les prénoms et les projets des élèves du groupe 2 nés entre janvier et mars 2005. *Il doit y avoir 6 élèves concernés (Aïris, Romain, Jade, Charles, Hugo, Kylian)*.

In [ ]:
# à vous de jouer !

**Question 3** : Construire une table `t7` contenant le prénom, l'année de naissance et l'âge de toutes les filles.

In [ ]:
# à vous de jouer !

# Bilan

- Les tables de données peuvent peuvent être mémorisées dans des fichiers et notamment dans des fichiers au format CSV.
- Pour traiter ces données (avec Python, ou avec un autre langage) il est nécessaire de *lire le fichier* et de *charger les données*. On a vu que le module `csv` permettait facilement de mémoriser les données d'une table dans un tableau de dictionnaires.
- On peut ensuite utiliser toutes les fonctionnalités du langage de programmation pour le traitement des données. En particulier, on peut y *rechercher des informations*, *sélectionner les colonnes* en fonction des attributs qui nous intéressent mais aussi *sélectionner des lignes* en fonction de certains *critères*.
- Ces traitements permettent de créer de nouvelles tables que l'on peut aussi *écrire* dans un fichier CSV pour garder une trace pérenne des informations calculées (fait en activité).
- Nous verrons au cours d'un TP l'intérêt de faire un *prétraitement* adapté des données pour répondre aux problématiques suivantes :
    - les données chargées dans un tableau le sont sous forme de chaînes de caractères, mêmes les nombres. Il peut donc être intéressant de les convertir une fois pour toutes au départ et éviter les conversions de type dans tous les traitements.
    - pour les données ouvertes obtenues sur des sites spécialisés, il convient d'être vigilant en cas de données manquantes ou de données particulières. On s'assurera donc que les données sont *cohérentes* avant de commencer à les traiter.

- Tout ce qui est fait sur le traitement des données en classe de Première est un avant-goût des bases de données qui seront étudiées en classe de Terminale.

**Sources :**
- Equipe pédagogique, DIU EIL, Univertité de Nantes.
- Livre *Numérique et Sciences Informatiques, 1re*, T. BALABONSKI, S. CONCHON, J.-C. FILLIATRE, K. NGUYEN, éditions ELLIPSES pour l'idée du plan de ce cours. Voici le [site du livre](https://www.nsi-premiere.fr/).
- Ressource Eduscol : [Manipulation de tables](https://bit.ly/2BL2lbA)

---
Germain BECKER & Sébastien POINT, Lycée Mounier, ANGERS ![Licence Creative Commons](https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png)